changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
      - github-actions
  categories:
    - title: Features
      labels:
        - "type: feature"
        - "type: enhancement"
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - "type: bug"
        - "type: bugfix"
        - bug
        - fix
        - bugfix
    - title: Improvements
      labels:
        - "type: improvement"
        - "type: refactor"
        - improvement
        - refactor
    - title: Documentation
      labels:
        - "type: docs"
        - "type: documentation"
        - documentation
        - docs
    - title: Dependencies
      labels:
        - dependencies
        - dependabot
    - title: Other Changes
      labels:
        - "*"

