import {
  ORDER_STATUS_VALUES,
  PAYMENT_COLLECTION_STATUS_VALUES,
  FULFILLMENT_STATUS_VALUES,
} from "./helpers"

// Attributes available in rules (without technical relations with *)
// These attributes are displayed in the UI for creating conditions in automations
export const ORDER_ATTRIBUTES = [
  // Basic fields
  {
    value: "order.id",
    label: "ID",
    description: "Unique identifier of the order",
    examples: ["order_01ABC123", "order_01XYZ789"],
  },
  {
    value: "order.display_id",
    label: "Display ID",
    description: "Human-readable order number displayed to customers",
    examples: ["#1001", "#2050", "#9999"],
  },
  {
    value: "order.custom_display_id",
    label: "Custom Display ID",
    description: "Custom order identifier set by the merchant",
    examples: ["CUSTOM-001", "PO-2024-001"],
  },
  {
    value: "order.status",
    label: "Status",
    description: "Current status of the order",
    examples: ORDER_STATUS_VALUES,
  },
  {
    value: "order.locale",
    label: "Locale",
    description: "Locale code for the order (language and region)",
    examples: ["pl", "en", "en-US", "pl-PL"],
  },
  {
    value: "order.email",
    label: "Email",
    description: "Customer email address associated with the order",
    examples: ["customer@example.com", "user@domain.com"],
  },
  {
    value: "order.currency_code",
    label: "Currency Code",
    description: "ISO 4217 currency code for the order",
    examples: ["USD", "EUR", "PLN", "GBP"],
  },
  {
    value: "order.region_id",
    label: "Region ID",
    description: "Unique identifier of the region",
    examples: ["reg_01ABC123"],
  },
  {
    value: "order.created_at",
    label: "Created At",
    description: "Date and time when the order was created (ISO 8601 format)",
    examples: ["2024-01-15T10:30:00Z", "2024-12-25T00:00:00Z"],
  },
  {
    value: "order.updated_at",
    label: "Updated At",
    description: "Date and time when the order was last updated (ISO 8601 format)",
    examples: ["2024-01-15T10:30:00Z", "2024-12-25T00:00:00Z"],
  },
  // Totals
  {
    value: "order.total",
    label: "Total",
    description: "Total amount of the order including taxes, shipping, and discounts",
    examples: ["100.00", "250.50", "999.99"],
  },
  {
    value: "order.subtotal",
    label: "Subtotal",
    description: "Subtotal amount before taxes and shipping",
    examples: ["80.00", "200.00", "850.00"],
  },
  {
    value: "order.tax_total",
    label: "Tax Total",
    description: "Total amount of taxes applied to the order",
    examples: ["20.00", "50.00", "149.99"],
  },
  {
    value: "order.original_total",
    label: "Original Total",
    description: "Original total amount before any changes or adjustments",
    examples: ["100.00", "250.50", "999.99"],
  },
  {
    value: "order.original_subtotal",
    label: "Original Subtotal",
    description: "Original subtotal before any changes or adjustments",
    examples: ["80.00", "200.00", "850.00"],
  },
  {
    value: "order.original_tax_total",
    label: "Original Tax Total",
    description: "Original tax total before any changes or adjustments",
    examples: ["20.00", "50.00", "149.99"],
  },
  {
    value: "order.discount_total",
    label: "Discount Total",
    description: "Total amount of discounts applied to the order",
    examples: ["0.00", "10.00", "50.00"],
  },
  {
    value: "order.discount_tax_total",
    label: "Discount Tax Total",
    description: "Tax amount on discounts applied to the order",
    examples: ["0.00", "2.50", "12.50"],
  },
  // Shipping (specific fields, not *)
  {
    value: "order.shipping_methods.amount",
    label: "Shipping Methods Amount",
    description: "Total shipping cost for all shipping methods. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["0.00", "10.00", "25.50"],
    type: "array",
    isRelation: true,
    relationType: "shipping_methods",
  },
  {
    value: "order.shipping_methods.subtotal",
    label: "Shipping Methods Subtotal",
    description: "Shipping subtotal before taxes. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["0.00", "8.00", "20.00"],
    type: "array",
    isRelation: true,
    relationType: "shipping_methods",
  },
  {
    value: "order.shipping_methods.tax_total",
    label: "Shipping Methods Tax Total",
    description: "Tax amount on shipping. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["0.00", "2.00", "5.50"],
    type: "array",
    isRelation: true,
    relationType: "shipping_methods",
  },
  {
    value: "order.shipping_methods.original_total",
    label: "Shipping Methods Original Total",
    description: "Original shipping total before adjustments. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["0.00", "10.00", "25.50"],
    type: "array",
    isRelation: true,
    relationType: "shipping_methods",
  },
  {
    value: "order.shipping_methods.original_subtotal",
    label: "Shipping Methods Original Subtotal",
    description: "Original shipping subtotal before adjustments. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["0.00", "8.00", "20.00"],
    type: "array",
    isRelation: true,
    relationType: "shipping_methods",
  },
  {
    value: "order.shipping_methods.original_tax_total",
    label: "Shipping Methods Original Tax Total",
    description: "Original shipping tax total before adjustments. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["0.00", "2.00", "5.50"],
    type: "array",
    isRelation: true,
    relationType: "shipping_methods",
  },
  {
    value: "order.shipping_methods.discount_total",
    label: "Shipping Methods Discount Total",
    description: "Total shipping discounts applied. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["0.00", "5.00", "10.00"],
    type: "array",
    isRelation: true,
    relationType: "shipping_methods",
  },
  {
    value: "order.shipping_methods.discount_subtotal",
    label: "Shipping Methods Discount Subtotal",
    description: "Shipping discount subtotal. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["0.00", "4.00", "8.00"],
    type: "array",
    isRelation: true,
    relationType: "shipping_methods",
  },
  {
    value: "order.shipping_methods.discount_tax_total",
    label: "Shipping Methods Discount Tax Total",
    description: "Tax amount on shipping discounts. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["0.00", "1.00", "2.00"],
    type: "array",
    isRelation: true,
    relationType: "shipping_methods",
  },
  // Summary (specific fields)
  {
    value: "order.summary.total",
    label: "Summary Total",
    description: "Summary total amount including all adjustments",
    examples: ["100.00", "250.50", "999.99"],
  },
  {
    value: "order.summary.subtotal",
    label: "Summary Subtotal",
    description: "Summary subtotal amount",
    examples: ["80.00", "200.00", "850.00"],
  },
  {
    value: "order.summary.tax_total",
    label: "Summary Tax Total",
    description: "Summary tax total amount",
    examples: ["20.00", "50.00", "149.99"],
  },
  {
    value: "order.summary.discount_total",
    label: "Summary Discount Total",
    description: "Summary discount total amount",
    examples: ["0.00", "10.00", "50.00"],
  },
  {
    value: "order.summary.original_order_total",
    label: "Summary Original Order Total",
    description: "Summary original order total before adjustments",
    examples: ["100.00", "250.50", "999.99"],
  },
  {
    value: "order.summary.current_order_total",
    label: "Summary Current Order Total",
    description: "Summary current order total after all adjustments",
    examples: ["100.00", "250.50", "999.99"],
  },
  {
    value: "order.summary.paid_total",
    label: "Summary Paid Total",
    description: "Total amount that has been paid for this order",
    examples: ["0.00", "100.00", "250.50"],
  },
  {
    value: "order.summary.refunded_total",
    label: "Summary Refunded Total",
    description: "Total amount that has been refunded for this order",
    examples: ["0.00", "50.00", "100.00"],
  },
  {
    value: "order.summary.accounting_total",
    label: "Summary Accounting Total",
    description: "Total amount for accounting purposes",
    examples: ["100.00", "250.50", "999.99"],
  },
  {
    value: "order.summary.credit_line_total",
    label: "Summary Credit Line Total",
    description: "Total amount from credit lines applied to this order",
    examples: ["0.00", "25.00", "100.00"],
  },
  {
    value: "order.summary.transaction_total",
    label: "Summary Transaction Total",
    description: "Total amount of all transactions for this order",
    examples: ["0.00", "100.00", "250.50"],
  },
  {
    value: "order.summary.pending_difference",
    label: "Summary Pending Difference",
    description: "Difference between expected and actual payment amounts",
    examples: ["0.00", "10.00", "-5.00"],
  },
  // Customer relation
  {
    value: "order.customer.id",
    label: "Customer ID",
    description: "Unique identifier of the customer who placed the order",
    examples: ["cus_01ABC123"],
    isRelation: true,
    relationType: "customer",
  },
  {
    value: "order.customer.email",
    label: "Customer Email",
    description: "Email address of the customer who placed the order",
    examples: ["customer@example.com"],
    isRelation: true,
    relationType: "customer",
  },
  {
    value: "order.customer.first_name",
    label: "Customer First Name",
    description: "First name of the customer",
    examples: ["John", "Jane", "Jan"],
    isRelation: true,
    relationType: "customer",
  },
  {
    value: "order.customer.last_name",
    label: "Customer Last Name",
    description: "Last name of the customer",
    examples: ["Doe", "Smith", "Kowalski"],
    isRelation: true,
    relationType: "customer",
  },
  // Sales channel relation
  {
    value: "order.sales_channel.id",
    label: "Sales Channel ID",
    description: "Unique identifier of the sales channel",
    examples: ["sc_01ABC123"],
    isRelation: true,
    relationType: "sales_channel",
  },
  {
    value: "order.sales_channel.name",
    label: "Sales Channel Name",
    description: "Name of the sales channel",
    examples: ["Default Channel", "Online Store", "Mobile App"],
    isRelation: true,
    relationType: "sales_channel",
  },
  // Shipping address
  {
    value: "order.shipping_address.first_name",
    label: "Shipping First Name",
    description: "First name for shipping address. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["John", "Jane"],
    isRelation: true,
    relationType: "shipping_address",
  },
  {
    value: "order.shipping_address.last_name",
    label: "Shipping Last Name",
    description: "Last name for shipping address. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["Doe", "Smith"],
    isRelation: true,
    relationType: "shipping_address",
  },
  {
    value: "order.shipping_address.address_1",
    label: "Shipping Address 1",
    description: "Primary street address for shipping. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["123 Main St", "456 Oak Ave"],
    isRelation: true,
    relationType: "shipping_address",
  },
  {
    value: "order.shipping_address.city",
    label: "Shipping City",
    description: "City for shipping address. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["Warsaw", "Krakow", "London"],
    isRelation: true,
    relationType: "shipping_address",
  },
  {
    value: "order.shipping_address.country_code",
    label: "Shipping Country Code",
    description: "ISO 3166-1 alpha-2 country code for shipping. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["PL", "US", "GB", "DE"],
    isRelation: true,
    relationType: "shipping_address",
  },
  {
    value: "order.shipping_address.postal_code",
    label: "Shipping Postal Code",
    description: "Postal/ZIP code for shipping address. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["00-001", "10001", "SW1A 1AA"],
    isRelation: true,
    relationType: "shipping_address",
  },
  // Billing address
  {
    value: "order.billing_address.first_name",
    label: "Billing First Name",
    description: "First name for billing address. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["John", "Jane"],
    isRelation: true,
    relationType: "billing_address",
  },
  {
    value: "order.billing_address.last_name",
    label: "Billing Last Name",
    description: "Last name for billing address. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["Doe", "Smith"],
    isRelation: true,
    relationType: "billing_address",
  },
  {
    value: "order.billing_address.address_1",
    label: "Billing Address 1",
    description: "Primary street address for billing. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["123 Main St", "456 Oak Ave"],
    isRelation: true,
    relationType: "billing_address",
  },
  {
    value: "order.billing_address.city",
    label: "Billing City",
    description: "City for billing address. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["Warsaw", "Krakow", "London"],
    isRelation: true,
    relationType: "billing_address",
  },
  {
    value: "order.billing_address.country_code",
    label: "Billing Country Code",
    description: "ISO 3166-1 alpha-2 country code for billing. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["PL", "US", "GB", "DE"],
    isRelation: true,
    relationType: "billing_address",
  },
  {
    value: "order.billing_address.postal_code",
    label: "Billing Postal Code",
    description: "Postal/ZIP code for billing address. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["00-001", "10001", "SW1A 1AA"],
    isRelation: true,
    relationType: "billing_address",
  },
  // Items (specific fields, not *)
  {
    value: "order.items.id",
    label: "Item ID",
    description: "Unique identifier of the order item. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["item_01ABC123"],
    type: "array",
    isRelation: true,
    relationType: "items",
  },
  {
    value: "order.items.quantity",
    label: "Item Quantity",
    description: "Quantity of this item in the order. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["1", "2", "5", "10"],
    type: "array",
    isRelation: true,
    relationType: "items",
  },
  {
    value: "order.items.title",
    label: "Item Title",
    description: "Title/name of the order item. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["T-Shirt", "Jeans", "Sneakers"],
    type: "array",
    isRelation: true,
    relationType: "items",
  },
  {
    value: "order.items.unit_price",
    label: "Item Unit Price",
    description: "Price per unit of this item. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["29.99", "99.99", "199.99"],
    type: "array",
    isRelation: true,
    relationType: "items",
  },
  {
    value: "order.items.variant.id",
    label: "Item Variant ID",
    description: "Unique identifier of the product variant. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["variant_01ABC123"],
    type: "array",
    isRelation: true,
    relationType: "items",
  },
  {
    value: "order.items.variant.sku",
    label: "Item Variant SKU",
    description: "SKU (Stock Keeping Unit) of the product variant. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["TSHIRT-SM-BLUE", "JEANS-32-BLACK"],
    type: "array",
    isRelation: true,
    relationType: "items",
  },
  {
    value: "order.items.product.id",
    label: "Item Product ID",
    description: "Unique identifier of the product. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["prod_01ABC123"],
    type: "array",
    isRelation: true,
    relationType: "items",
  },
  {
    value: "order.items.product.title",
    label: "Item Product Title",
    description: "Title/name of the product. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["T-Shirt", "Jeans", "Sneakers"],
    type: "array",
    isRelation: true,
    relationType: "items",
  },
  // Payment collections
  {
    value: "order.payment_collections.id",
    label: "Payment Collection ID",
    description: "Unique identifier of the payment collection. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["paycol_01ABC123"],
    type: "array",
    isRelation: true,
    relationType: "payment_collections",
  },
  {
    value: "order.payment_collections.status",
    label: "Payment Collection Status",
    description: "Status of payment collections for this order. This is an array - operator 'eq' checks if ANY value matches",
    examples: PAYMENT_COLLECTION_STATUS_VALUES,
    type: "array",
    isRelation: true,
    relationType: "payment_collections",
  },
  {
    value: "order.payment_collections.amount",
    label: "Payment Collection Amount",
    description: "Amount of the payment collection. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["100.00", "250.50", "999.99"],
    type: "array",
    isRelation: true,
    relationType: "payment_collections",
  },
  // Fulfillments
  {
    value: "order.fulfillments.id",
    label: "Fulfillment ID",
    description: "Unique identifier of the fulfillment. This is an array - operator 'eq' checks if ANY value matches",
    examples: ["ful_01ABC123"],
    type: "array",
    isRelation: true,
    relationType: "fulfillments",
  },
  {
    value: "order.fulfillments.status",
    label: "Fulfillment Status",
    description: "Status of fulfillments for this order. This is an array - operator 'eq' checks if ANY value matches",
    examples: FULFILLMENT_STATUS_VALUES,
    type: "array",
    isRelation: true,
    relationType: "fulfillments",
  },
]

// Fields for use in query.graph() - includes technical relations with *
// These fields are required for correct totals calculation by OrderModuleService
// ORDER_QUERY_FIELDS contains all fields from ORDER_ATTRIBUTES plus technical relations
export const ORDER_QUERY_FIELDS = [
  // Basic fields from ORDER_ATTRIBUTES
  ...ORDER_ATTRIBUTES.map((attr) => attr.value),
  
  // Technical relations required for totals calculation
  // These fields are not available in UI rules, but are needed for correct data retrieval
  "order.items.*",
  "order.items.tax_lines.*",
  "order.items.adjustments.*",
  "order.shipping_methods.*",
  "order.shipping_methods.tax_lines.*",
  "order.shipping_methods.adjustments.*",
  "order.fulfillments.*",
  "order.credit_lines.*",
  "order.summary.*",
]
